name: commit-checks
on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
  cover:
    name: code-coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'
    - name: Generate coverage
      run: |
        go test -race -coverprofile=cover.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./cover.out
        verbose: true
